export const supported_languages = [
    { label: "English (US)", value: "en" },
    { label: "English (UK)", value: "en-uk" },
    { label: "Hindi", value: "hi" },
    { label: "Spanish", value: "es" },
    { label: "French", value: "fr" },
    { label: "Japanese", value: "ja" },
    { label: "Czech", value: "cs" },
    { label: "Dutch", value: "nl" },
    { label: "Slovak", value: "sk" },
    { label: "Russian", value: "ru" },
    { label: "German", value: "de" },
    { label: "Italian", value: "it" },
    { label: "Korean", value: "ko" },
    { label: "Brazilian Portuguese", value: "pt-BR" },
    { label: "Arabic", value: "ar" },
    { label: "Turkish", value: "tr" },
]